### ISSUE TITLE
Nebulas segwit support discuss

### ISSUE THREAD

**Issue by qywang2012** [nebulasio/go-nebulas#38]
Nebulae are discussing whether to use Segregated Witness. Should we need to separate the signatures from transaction body? 

[segwit](https://en.wikipedia.org/wiki/SegWit)

Anyone can comment on this and discuss it.

**Comment by smartpunter** [comment]
As long, as there is no mainnet and you are free to broke everything, and you feel like you are capable of implementing it, there is no reason not to do this, working with segwit protocol is a bit easier for developers, because txid is guaranteed to be intact.

Some interesting reading here:
https://bitcoincore.org/en/2016/01/26/segwit-benefits/

**Comment by fbzhong** [comment]
After reading some articles, the segwit is used to solve the txid issue in bitcoin, which is not exist in nebulas protocol.

It seems like the only benefit of segwit liked design is "less transaction data size (-65bytes)" in Chunk Sync mode.

Let me know when I miss anything.

**Comment by smartpunter** [comment]
Well, i also thought at the beginning, that segwit is not necessary for pos consensus blockchains...

Do you think it would be possible to make such changed in block structure later, using Protocol Code? If yes, than it is easy decision not to bother with SegWit now. If no, than we need some other opinions :)

**Comment by fbzhong** [comment]
Seems like the issue related to Segwit does not exist in Nebulas.

Close this issue.
