### ISSUE TITLE
Parameters of EstimateGas api 

### ISSUE THREAD

**Issue by bitcodernull** [nebulasio/go-nebulas#83]
why do the parameters of EstimateGas api  need gasprice/gaslimte/nonce?
thanks

**Comment by nebulashub** [comment]
because this API's parameters are equal to `sendTransaction`. The node create a transaction and simulate execution, so these parameters are necessary. 

For `EstimateGas` API
- `gasPrice`: equal to the real gasPrice you want to execute
- `gasLimit`: give a default `gasLimit`, which between 0 and 50000000000. It should have a value but it won't affect the result.
- `nonce`: It should have a value but it won't affect the result.

**Comment by bitcodernull** [comment]
thanks
